[package]
name = "pseudomanager-api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
actix-rt = "2.0"
serde = "1.0.136"
serde_json = "1.0.59"